### ISSUE TITLE
parser: implement access-to-member operator

### ISSUE THREAD

**Issue by 0verse** [mini-rose/coffee#13]
The caffee code below results with:

> zsh: segmentation fault  nxg -o struct struct.ff

```
type User {
    name: str
    age: i32
}

fn main() {
    user: User = User{name: "Ali", age: 43}
    print(user.name)
    print(user.age)

}
```

**Comment by bellrise** [comment]
Not implemented yet, objects are probably next in line

**Comment by 0verse** [comment]
ok, good to know :)

**Comment by bellrise** [comment]
Added in 4d2592b

**Comment by 0verse** [comment]
Nice done! However, I get this error with the above code:

> error in struct.ff:
> 
> 6	    user: User = User{name: "Ali", age: 43}
> 	                 ^~~~ use of undeclared variable

I could work around the error like this: 
```
    user: User
    user.name = "ali"
    user.age = 43
```
But another error on the codegen side:
> ERROR: emit: missing `fn drop(&User { str i32 })`
