### ISSUE TITLE
Extending c module segfaults

### ISSUE THREAD

**Issue by 0verse** [mini-rose/coffee#14]
I try to invoke the system() function from c but all I get is a segfault.

process.c:
```
#include<stdlib.h>

int runcmd(const char* cmd) {
    return system(cmd);
}
```
process.ff:
```
fn runcmd(cmd: str) {
    __builtin_decl("runcmd", null, str)
    runcmd(cmd)
}
```
run_ls.ff:
```
use "process"

fn main() {
    ls: str = "ls -l"
    runcmd(ls)
}
```
output:

> özcü@özcül ~/çizeylemcil/coffee # nxg -o run_ls run_ls.ff 
> özcü@özcül ~/çizeylemcil/coffee # ./run_ls 
> zsh: segmentation fault  ./run_ls

**Comment by bellrise** [comment]
The problem with your code is the const char * parameter. `str` is internally a struct-like object, and not a regular const char *. In the "Extending with C" section it's said that passing structs to C is problematic and, most likely, will result in a segfault like your case. Instead, `runcmd` in C should take a:

```c
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

struct str {
   int64_t len;
   char *ptr; 
   int32_t _0;
};

int runcmd(struct str *cmd) {
    char *tmp;
    int ret;
   
    /* We make a strndup here, because strings in Coffee are not null-terminated. */
    tmp = strndup(cmd->ptr, cmd->len);
    ret = system(tmp);
    
    free(tmp);
    return ret;
}
```

```rs
fn runcmd(cmd: str) {
    __builtin_decl("runcmd", null, &str)
    runcmd(&cmd)
}
```

I haven't tested this, but it should work.

**Comment by bellrise** [comment]
As for the segfault, it was most likely a recursion error which are now simply errors from the builtin stacktrace module.
