### ISSUE TITLE
missing named func _C5print3str

### ISSUE THREAD

**Issue by 0verse** [mini-rose/coffee#17]
These coffee files used to compile before, now I get an error message instead.

strinc.ff:
```
use std.io

fn print_str(s: str) {
    print(s)
}
```
hello.ff:
```
use "strinc"

fn main() {
    hw: str = "hello world"
    print_str(hw)
}
```
error:
> ERROR: emit: missing named func _C5print3str

**Comment by bellrise** [comment]
Fixed as of a79b2d1

**Comment by 0verse** [comment]
thanks, it compiles now but segfaults when executed:
> zsh: segmentation fault  ./hello

**Comment by 0verse** [comment]
awesome bellrise :) works well as before!
