### ISSUE TITLE
Bool type assign is not working

### ISSUE THREAD

**Issue by fenze** [mini-rose/coffee#29]
```rust
fn main {
    x = true
    print(x)
}
```

Causes this error: use of undeclared variable at 'true' name

**Comment by bellrise** [comment]
Please add T_TRUE and T_FALSE tokens for this.

**Comment by fenze** [comment]
Added in [#d79f08c](https://github.com/mini-rose/coffee/commit/d79f08c77833a40e4d26b1b2cc62be1d34764318)

**Comment by fenze** [comment]
Fixed as of https://github.com/mini-rose/coffee/commit/d67e5f43eb57bf9c12e5fe0702c6eeb97fc18b2f

**Comment by 0verse** [comment]
neat :)
