### ISSUE TITLE
musl: cannot find libasan

### ISSUE THREAD

**Issue by 0verse** [mini-rose/coffee#33]
@fenze reintroduced '-fsanitize=address' in meson.build, which leads to this error: 

> /an/duyum/etki/ld: cannot find libasan_preinit.o: No such file or directory
> /an/duyum/etki/ld: cannot find -lasan: No such file or directory
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.

**Comment by 0verse** [comment]
maybe we could write a function in meson.build to detect glibc and then use '-fsanitize=address' option

**Comment by 0verse** [comment]
like this?:
```
cc = meson.get_compiler('c')
libasan_dep = cc.find_library('asan', required: false)
sanitize = ''
if libasan_dep.found()
    sanitize = '-fsanitize=address'
endif

exe = executable(
  'nxg', sources,
  include_directories: includes,
  c_args: ['-O2', '-g', sanitize, '-DNXG_LIB="' + libdir + '"'],
  link_args: ['-Wall', '-Wextra', '-pedantic', sanitize],
...
```

**Comment by bellrise** [comment]
`nxg` won't build with any sanitizers, this way just a mishap by fenze, this flag should not be pushed onto master.
